[Kai] 기존 BoardCollectionViewCell 역할 을 ChildViewController 에게 분담시키기
BumgeunSong/Krello pull request #52
Opened 2022-05-18 09:04 UTC by TaeKyeongKim

## 📙 작업 내역
- #51 

## 🤔 고민과 해결
### 고민 1.0  : BoardCollectionViewCell 역할을 분담 시키기에 크게 2 가지 옵션이 있었습니다. 
  - 1.0 `BoardViewController` 가 모든 delegation 과 데이터 업데이트 을 수행한다.
     - 장점 :  모든 로직을 `BoardViewController` 가 가지고 있으므로 구현이 쉽다. 
     - 단점 : `BoardViewController` 가 너무 커지고 코드를 이해하기 힘들어진다.
        
  - 2.0 새로운 `viewController` 에 `BoardCollectionViewCell` 의 delegation 과 dataSource 업데이트 로직을 분담시킨다. 
       - 장점:  `BoardViewController` 과 새로운 `viewController` 의 역할에 따른 로직을 분리시킬수 있기때문에 Massive VC 를 피할수있고, 코드를 이해하기 쉬워진다. 
       - 단점: 각 VC 의 역할을 분명히 나눌수 있어야 역할이 나뉜것을 똑바로 이해할수 있기때문에 잘못 구현할시 코드가 더욱 복잡해 질수 있다. 

### 해결 
- `BoardViewController` 모든 로직을 가지고 있으면 VC 가 너무 커지고 코드의 재사용성 이 떨어지기 때문에 새로운 VC 를 만들어 역할을 분담 시켰습니다. 
- 새로운 ViewController 의 이름은 `TaskViewController` 라 정했고, task 에 관한 모든 역할을 수행하도록 설계했습니다. 
----
### 고민 2.0  : `TaskViewController` 를 어디에 배치시킬까 ? 
  - 1.0 `BoardCollectionViewCell` 안에 `TaskViewController` 를 프로퍼티로 할당시킨다.
     - 장점 :  Cell 의 reusability life cycle 을 고려하지 않아도 된다.  (구현이 쉬움) 
     - 단점 :  Cell 과 `TaskViewController` 의 의존성이 높아져서 재사용성이 떨어지고, test 가 어려워진다.
        
  - 2.0 `TaskViewController` 를 BoardViewController 의 childViewController 로 만든다.
       - 장점: 느슨한 결합으로 구현가능하다. 
       - 단점: 하나의 cell 에 여러개의 childVC 가 생성되지 않도록 신경써야함. (구현이 어렵다)
      
### 해결 
- `TaskViewController` 를 BoardViewController 의 childViewController 로 만드는 방식을 선택했습니다. 
- 그 이유는 Cell 이 `TaskViewController` 를 알게 되면 1.0 의 단점이 있을 뿐만아니라 taskVC 가 데이터를 전달 받는 방식이 cell 을 거치고 해야하기 때문에 코드가 복잡해질수 있기때문입니다. 
- 2.0 방법은 cell 의 life cycle 과 addSubView, removeSubView 되는 시점에 대한 이해가 필요해서 구현이 조금 어렵긴하지만, cell 과 boardViewController 사이에 느슨한 결합으로 구현할수 있어서 2.0 방법으로 구현해봤습니다. 
<p align="center">
   <img src="https://user-images.githubusercontent.com/36659877/168995627-55370b6a-acae-47ae-9097-aa0c4ced66a0.png" width="500" height="500"> 
</p>

## 💭 기타 설명
### Task 타입 수정 
NSItemProvider 는 데이터나 파일을 drag and drop 이나 copy/paste 작업중에 사용 되는 `item provider` 클래스. 
그리고 TableView Drag and Drop 에서 사용되는 NSItemProvider 는 NSItemProviderWriting, NSItemProviderReading 를 준수하고 있어야함. 기본적으로 이 두개의 프로토콜을 채택하고 있는 클래스들은  NSString, NSAttributedString, NSURL, UIColor, UIImage 등이 있기때문에 바로 Drag and Drop이 가능함.
하지만 위의 타입외의 사용자 별도 타입으로도 사용 하려면  NSItemProviderWriting, NSItemProviderReading 프로토콜을 준수하도록 해야 한다. 따라서 현재 프로젝트의 Task 타입을 위의 프로토콜을 따르도록 수정. 
[참고](https://velog.io/@panther222128/Drag-and-Drop-Issue)

2022-05-18 12:17 UTC, BumgeunSong commented on Krello/BoardCRUD/Controller/BoardViewController.swift
> +        ])
🟡  혹시 이 레이아웃 코드를 BoardCollection Cell로 옮기고, 외부(BoardVC)에서 요청을 하는 방식으로 변경할 수는 없을까요? 레이아웃 코드는 뷰의 책임으로 두는 게 MassiveViewController를 방지하는데 도움이 될 듯합니다

2022-05-18 12:19 UTC, BumgeunSong commented on Krello/BoardCRUD/View/BoardCollectionViewCell.swift
> +    }
❓ DidEndDisplaying이랑 prepareForReuse에 remove를 두번 호출하는 것 같은데 이유가 있을지?

![cell-lifecycle](https://user-images.githubusercontent.com/17468015/169037150-39ce7a02-00d2-4541-9558-8ddf3231e50a.png)

2022-05-18 12:20 UTC, BumgeunSong commented on Krello/Login/Model/Firestore/FirestoreService.swift
> +
🟢  와 이런걸 따로 해줘야 하는구나 너무 고생했다 👍

2022-05-18 12:23 UTC, BumgeunSong commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    }
🟡  저번에 [노션](https://cookie-giant-a00.notion.site/0517-d0e5f1b114ca4e43ab40e0e25b55228c)에 적었던 것처럼 
ViewController가 해야하는 view 관련된 코드를 constraints, display, subview 를 세가지 함수로 나눠서 정리해준다면 훨씬 더 좋을 거 같습니다!

2022-05-18 12:24 UTC, BumgeunSong commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +            self.tasks = self.taskService.fetch(status: self.status)
🔴  fetch를 요청하는 코드는 main.async 작업에서 빼야 백그라운드에서 효율적으로 돌아갈 수 있을 것 같네요! 가져온 데이터를 UI에 세팅하는 부분만 main.async 작업으로

2022-05-18 12:26 UTC, BumgeunSong commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    func tableView(_ tableView: UITableView, performDropWith coordinator: UITableViewDropCoordinator) {
🔵  이 부분은 (내가 쓴 거지만) 나중에 함수를 더 작게 쪼개고 중복을 줄여서 개선해보면 좋을 거 같습니다!

2022-05-18 12:28 UTC, BumgeunSong commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    func fetch(status: String) -> [Task] {
🟡  status Enum이 있으니 string 말고 enum을 사용하는게 어떨지?

2022-05-18 12:29 UTC, BumgeunSong requested changes
와우 👏  코드 훌륭하고 훨씬 더 깔끔해진 거 같네요. ViewController 라이프 사이클 관리하는 거랑 ItemProvider 관련 디버깅 쉽지 않았을 텐데 잘한 듯! 몇가지 사항만 수정하고 merge하면 될 거 같네요. 

다음 PR에서는 Datasource나 Delegate를 분리하는 것까지 가보면 어떨까 싶습니다. 👍

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/BoardCRUD/Controller/BoardViewController.swift
> +        ])
저도 이부분을 좀 바꾸고 싶었는데 좋은 아이디어네용!

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/BoardCRUD/View/BoardCollectionViewCell.swift
> +    }
우리 화면에 cell 이 살짝 살짝 걸쳐져 있어서 다음 Cell 로 넘어가도 Dequeue 가 안되는것 같더라고요? 
ex) Cell 1 에서 Cell 2 로 넘어가도 Cell 1 이 화면에 걸처 있기 때문에 Dequeue 안됨.
그래서 DidEndDisplaying 를 써서 cellForItemAt 이 Cell 2 이면 Cell 1 을 remove 해주도록 해놓은 상태입니다.

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/Login/Model/Firestore/FirestoreService.swift
> +
저 코드를 다 이해하려면 오래 걸릴것같아서 일단 배껴왔써요.. Task 수정하다가 Hashable 이 빠져서 수정이 필요합니닷!

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    func fetch(status: String) -> [Task] {
넵 나이스케치!

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    func tableView(_ tableView: UITableView, performDropWith coordinator: UITableViewDropCoordinator) {
넵 ~!

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    }
넵 알겠습니답 !

2022-05-18 13:59 UTC, TaeKyeongKim commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +            self.tasks = self.taskService.fetch(status: self.status)
앗 ! 나이스 케치!

2022-05-19 01:00 UTC, Jinsujin approved these changes
고민많이 한 만큼 좋은 구조로 변하고 있는 것 같습니다!
정리를 잘 해 주셔서 흐름에 대한 이해도 잘 되네요. 큰 고비는 넘겼으니 디테일한 부분 손 보시면 될 것 같아요!
View에 보여져야 할 Model 에 대한 테스트도 추가해보면 좋을 것 같아요

2022-05-19 01:00 UTC, Jinsujin commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +        coordinator.session.loadObjects(ofClass: Task.self) { [weak self] items in
🟡  .(점) 으로 많이 연결되어 있어 가독성이 떨어지는 것 같습니다 개선할 수 있으면 좋겠네요

2022-05-19 01:00 UTC, Jinsujin commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +    private let taskService: TaskFetching = TaskServiceMock()
오우 네이밍 적용 하셨군요! 👏🏻👏🏻👏🏻

2022-05-19 01:00 UTC, Jinsujin commented on Krello/Login/Model/Firestore/FirestoreService.swift
> +            fatalError()
🔴 fatalError 는 앱을 강제종료 시키는데 여기 위치하는건 위험하지 않을까요? 에러처리 방법을 달리해야할 필요가 있어보입니다

2022-05-19 02:24 UTC, TaeKyeongKim commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +        coordinator.session.loadObjects(ofClass: Task.self) { [weak self] items in
이부분은 drag and drop delegation 따로 빼주면서 고쳐보도록 하겠습니닷!

2022-05-19 04:07 UTC, BumgeunSong commented on Krello/BoardCRUD/View/BoardCollectionViewCell.swift
> +    }
음 그러면 DidEndDisplaying에서 한번만 호출해주면 되는 거 아닐까요? 

어차피 `Cell 1`이 DidEndDisplaying에서 remove를 했으면, `Cell 1` Dequeue할 때는 ViewController가 제거된 상태 아닐까요?

2022-05-19 04:11 UTC, BumgeunSong commented on Krello/BoardCRUD/View/BoardCollectionViewCell.swift
> +    }
음, 내가 잘 이해한지 모르겠는데... 
지금 TaskViewController가 '가운데 온 Cell에 대해서만 생성'된 상태여야 해서 그런건가요?

우리 화면 디자인상 Cell은 항상 3개쯤 걸쳐서 보여지게 되어있을텐데, ToDoCell이 옆에 살짝 보여지고 있다면 TaskVC(status: Todo)는 삭제되어야 하나요? 

제가 이해한 바에 따르면 
현재 화면에 InProgress Cell이 가운데에 와있는 상황을 가정했을 때 다른 셀들이 옆에 살짝 보이잖아요? 
그래서 TaskVC (status: Todo), TaskVC (status: InProgress), TaskVC (status: Done) 3개가 모두 생성되어있을거라고 가정했는데 🤔

2022-05-19 04:36 UTC, BumgeunSong commented on Krello/TaskCRUD/Controller/TaskViewController.swift
> +        ])
🟡  저는 Constraints는 View의 책임이라고 생각이 들어서, `NSLayoutConstraint`가 있으면 뭔가 View로 넘겨주고 VC가 call만 하는 방식이 어떨까 하는 생각이 듭니다.

2022-05-19 04:36 UTC, BumgeunSong approved these changes

2022-05-19 05:06 UTC, merged